### ISSUE TITLE
Doc - Coordinate Conversion: Supported vs Non-Supported coordinate notation

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#794]
@dfoll @Dbarnes1 @adgiles FYI.
### Widget
Coordinate Conversion
### Version of widget
16 Jan 2017 10:41

Because we may not be able to modify the widget to use the same RegEx statements that the addins use (see https://github.com/Esri/solutions-webappbuilder-widgets/issues/727#issuecomment-272920738), I went ahead and performed a comparison between the supported notations between the Pro/ArcMap addins and the widget. Shown below are the results. The screenshots are what is supported by the Pro/Arcmap addins. If text is green then addin notation is also supported in widget. If text is red then addin notation is NOT supported in widget. See comments for issues and other info

## Decimal Degrees (DD)
![image](https://cloud.githubusercontent.com/assets/4635490/22004925/42292776-dc14-11e6-83fb-e113c50e757d.png)
- [ ] **ISSUE #800**: Widget partially supports +/- as suffix. For example...
Widget will create correct output for: 45.0+ 100.0- and 45.0+ 100.0+, but will create incorrect output for 45.0- 100.0- and 45.0- 100.0+. Either we fix this for this release or remove +/- suffix support.
- [ ] **ISSUE #801**: Widget supports hemisphere prefix [N|S|E|W] for DMS, but not for DD or DDM. We should fix this.
- [x] Widget will support spaces between the lat/long value and hemisphere suffix [N|S|E|W] for example 45.0 N 100.0 W. This is not supported by addins. Adjust content in doc table accordingly.

![image](https://cloud.githubusercontent.com/assets/4635490/22005265/90b25a0a-dc16-11e6-9ecc-396e00e86460.png)

## Degree Decimal Minutes (DDM)
![image](https://cloud.githubusercontent.com/assets/4635490/22005164/f8c61af6-dc15-11e6-8abc-02002b4ecb95.png)
- [ ] **ISSUE #800**: Widget partially supports +/- as suffix. For example...
Widget will create correct output for: 45 0.0+ 100 0.0- and 45 0.0+ 100 0.0+, but will create incorrect output for 45 0.0- 100 0.0- and 45 0.0- 100 0.0+. Either we fix this for this release or remove +/- suffix support.
- [ ] **ISSUE #801**: Widget supports hemisphere prefix [N|S|E|W] for DMS, but not for DD or DDM. We should fix this.
- [x] Widget will support spaces between the lat/long value and hemisphere suffix [N|S|E|W] for example 45 0.0 N 100 0.0 W. This is not supported by addins. Adjust content in doc table accordingly.

![image](https://cloud.githubusercontent.com/assets/4635490/22005405/b8e46832-dc17-11e6-953e-b03a8b48e7cf.png)

## Degree Minute Seconds (DMS)
![image](https://cloud.githubusercontent.com/assets/4635490/22005716/63db33e0-dc1a-11e6-853c-25f2c6f439cf.png)
- [ ] **ISSUE #800**: Widget partially supports +/- as suffix. For example...
Widget will create correct output for: 45 0 0.0+ 100 0 0.0- and 45 0 0.0+ 100 0 0.0+, but will create incorrect output for 45 0 0.0- 100 0 0.0- and 45 0 0.0- 100 0 0.0+. Either we fix this for this release or remove +/- suffix support.
- [x] Widget will support spaces between the lat/long value and hemisphere suffix [N|S|E|W] for example 45 0 0.0 N 100 0 0.0 W. This is not supported by addins. Adjust content in doc table accordingly.

![image](https://cloud.githubusercontent.com/assets/4635490/22006185/e2a8513c-dc1d-11e6-8cff-b1fd4277ab20.png)
- [ ] The widget supports using the Diaeresis ¨ (U+00A8) character for seconds mark (addins do not at all) only when used in conjunction with any of the degree-mark and minute-mark. If this character is used for seconds-mark and no degree-mark and minute-mark is used then widget can't interpret the coordinate. Add this character to the seconds-mark table in the doc and add a note about this limitation.

## Military Grid Reference System (MGRS)
- Same info from Pro/ArcMap addins apply to the widget.
- [x] We need to put a note in the doc that if any coordinates that may be in the MGRS/USNG/UTM output textboxes are invalid when input coordinate is in the polar regions (outside of 84N and 80S).

## United States National Grid (USNG)
- Same info from Pro/ArcMap addins apply to the widget.
- [x] We need to put a note in the doc that if any coordinates that may be in the MGRS/USNG/UTM output textboxes are invalid when input coordinate is in the polar regions (outside of 84N and 80S).

## Universal Traverse Mercator (UTM)
- Same info from Pro/ArcMap addins apply to the widget.
- [x] We need to put a note in the doc that if any coordinates that may be in the MGRS/USNG/UTM output textboxes are invalid when input coordinate is in the polar regions (outside of 84N and 80S).

**Comment by nfeuerstein** [comment]
This one is a duplicate: https://github.com/Esri/solutions-webappbuilder-widgets/issues/752

**Comment by Dbarnes1** [comment]
#800 and #801 have been logged as separate issues, and we should discuss them in war room tomorrow.

**Comment by lfunkhouser** [comment]
@elinz almost complete. Can you verify this is still an issue. I wasn't able to reproduce:
The widget supports using the Diaeresis ¨ (U+00A8) character for seconds mark (addins do not at all) only when used in conjunction with any of the degree-mark and minute-mark. If this character is used for seconds-mark and no degree-mark and minute-mark is used then widget can't interpret the coordinate. Add this character to the seconds-mark table in the doc and add a note about this limitation.

**Comment by elinz** [comment]
@lfunkhouser I tested the latest build and I'm not having any issues with the Diaeresis ¨ (U+00A8) for seconds-mark. You can use the Diaeresis ¨ (U+00A8) in combination with all the other degree-mark and minute-marks.

But now I'm having problems using the Masculine Ordinal Indicator º (U+00BA) for degree-mark.
All combinations of minutes/seconds using Masculine Ordinal Indicator for degree do not work except for: 
Masculine Ordinal Indicator º (U+00BA) Minute Sign ′ (U+2032) Double Acute Accent ˝ (U+02DD)
45º  0′ 0.0˝N 100º  0′ 0.0˝W

So what we should do is remove the Masculine Ordinal Indicator º (U+00BA) from supported degree-mark for the widget.

**Comment by elinz** [comment]
@lfunkhouser FYI. I check the last few builds and I don't see any of the doc changes listed in this issue in the .pdfs.

**Comment by nfeuerstein** [comment]
Next steps:
Remove masculine ordinal indicator
Kick off publish of doc
Kick off build
@elinz will verify and close

**Comment by adgiles** [comment]
@elinz 

My mistake I stupidly copied the characters being used on the pro help page that are not correct, the symbol they are using for Degree Sign and Ring Above are the same. The widget should now except the following three symbols: °˚º

**Comment by elinz** [comment]
@adgiles I'm assuming these Unicode characters:
Degree Sign ° (U+00B0)
Ring Above ˚ (U+02DA)
Masculine Ordinal Indicator º (U+00BA)

**Comment by adgiles** [comment]
Correct

**Comment by elinz** [comment]
@topowright @Dbarnes1 Don't remove the Remove masculine ordinal indicator degree symbol yet from the doc. @adgiles made a fix. I'm testing all the combinations of degree, minutes, seconds symbols for DD, DDM, and DMS.

**Comment by elinz** [comment]
@topowright @Dbarnes1 I finished testing all the combinations of symbols. They are all working so leave the masculine ordinal indicator degree symbol in the doc.

**Comment by Dbarnes1** [comment]
@elinz, I'll make sure to put it back in. Thanks for testing!

**Comment by Dbarnes1** [comment]
ready to verify in the next build.

**Comment by Dbarnes1** [comment]
@elinz and I just made some final changes to the doc regarding coordinate support, now it should be ready for final verification.

**Comment by elinz** [comment]
Verified in web app builder .pdf build 19 Jan 2017 13:18 #1155. Closing issue.
